name: sable_sky
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_native_splash: ^2.4.4
  weather: ^3.1.1
  geolocator: ^13.0.2
  http: ^1.3.0
  video_player: ^2.9.2
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env



